FROM golang:1.15

WORKDIR /opt/app

RUN apt update && apt install -y --no-install-recommends clang \
  && rm -rf /var/lib/apt/lists/*
ADD . .
RUN clang -v -c -std=gnu89 -target x86_64-pc-win32-mingw -DJATTACH_VERSION=\\"1.5\\" -o jattach.o jattach.c && clang -shared -o jattach.dll jattach.o
RUN GO111MODULES=on GOOS=windows GOARCH=amd64 CC=gcc CGO_ENABLED=1 go build .
